pre-commit:
  commands:
    format:
      files: git ls-files
      glob: '*.{py}'
      run: pixi run ruff format {staged_files}
      stage_fixed: true
    check:
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: pixi run ruff check {staged_files}
      stage_fixed: true
    clean-jupyter:
      files: git ls-files
      glob: '*.ipynb'
      run: pixi run jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    types:
      files: git ls-files
      glob: '*.py'
      run: pixi run ty check {staged_files}
    lychee:
      run: pixi run lychee . --suggest --max-concurrency 32 --cache --format detailed --max-cache-age 7d