from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Any, Sequence


DocumentId = str


@dataclass(slots=True)
class Chunk:
    """
    Atomic retrievable semantic unit of a document.

    A Chunk represents a deterministic fragment of a source document that can be
    independently embedded, indexed, retrieved and deleted.

    Identity
    --------
    The unique identity of a chunk is defined by the pair:
        (document_id, chunk_index)

    This identity MUST remain stable across re-indexing runs as long as the
    underlying document content has not changed in that region.

    Fields
    ------
    document_id : DocumentId
        Stable identifier of the parent document.
        Must remain constant across synchronization cycles.

    chunk_index : int
        Monotonically increasing positional index within the document.
        Defines ordering and chunk identity.
        Must not depend on runtime factors (timestamps, randomness, hashing).

    text : str
        Exact textual content used to generate the embedding.
        Any change to this text requires overwriting the stored vector.

    vector : Sequence[float]
        Embedding vector representing the semantic meaning of `text`.

        Requirements:
        - Fixed dimensionality across entire index
        - Generated by a single embedding model
        - Deterministic for identical input text

    metadata : Mapping[str, Any] | None
        Optional lightweight structured information about the chunk
        (e.g., page number, heading, section).

        Constraints:
        - Must be JSON-serializable
        - Must NOT affect chunk identity
        - Safe to drop without breaking retrieval correctness
    """

    document_id: DocumentId
    chunk_index: int
    text: str
    vector: Sequence[float]
    # optional lightweight metadata (page, section, etc)
    metadata: Mapping[str, Any] | None = None
