from __future__ import annotations

from typing import Sequence, List
from hashlib import blake2b

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    VectorParams,
    PointStruct,
    Filter,
    FieldCondition,
    MatchValue,
)

from database_builder_libs.models.chunk import Chunk, DocumentId
from database_builder_libs.models.abstract_vector_store import AbstractVectorStore


DOC_ID = "document_id"
CHUNK_INDEX = "chunk_index"
TEXT = "text"


class QdrantDatastore(AbstractVectorStore):
    """
    Qdrant implementation of the semantic vector store.

    Stores `Chunk` embeddings and enables similarity-based retrieval.

    Conceptual model
    ----------------
    Document → multiple Chunks → embedding vectors → nearest neighbour search

    Identity
    --------
    Each chunk is uniquely identified by:
        (document_id, chunk_index)

    This pair is deterministically mapped to a stable Qdrant point id using hashing.
    Re-indexing the same document overwrites existing vectors instead of duplicating them.

    Stored payload
    --------------
    Each vector stores:
        document_id
        chunk_index
        text
        metadata...

    Retrieval never returns embeddings — only semantic matches.

    Consistency guarantees
    ----------------------
    - Idempotent writes (upsert)
    - Stable ranking for unchanged index
    - No duplicate chunks returned
    - Full document deletion removes all vectors (GDPR requirement)

    Embedding requirements
    ----------------------
    All stored vectors must:
    - Match configured dimensionality
    - Be generated by the same embedding model
    - Use cosine similarity
    """

    def __init__(self) -> None:
        super().__init__()
        self.client: QdrantClient | None = None
        self.collection: str | None = None
        self.vector_size: int | None = None

    def _connect_impl(self, config: dict | None) -> None:
        if not config:
            raise ValueError("Qdrant requires configuration")

        url = config.get("url")
        collection = config.get("collection")
        vector_size = config.get("vector_size")

        if not url or not collection or not vector_size:
            raise ValueError("Qdrant config requires url, collection, vector_size")

        self.client = QdrantClient(url=url)
        self.collection = collection
        self.vector_size = int(vector_size)

        existing = {c.name for c in self.client.get_collections().collections}

        if self.collection not in existing:
            self.client.create_collection(
                collection_name=self.collection,
                vectors_config=VectorParams(
                    size=self.vector_size,
                    distance=Distance.COSINE,
                ),
            )


    def _point_id(self, document_id: DocumentId, chunk_index: int) -> int:
        """
        Deterministically map a chunk identity to a Qdrant point id.

        The mapping guarantees:
        - Stable ID across re-indexing
        - Overwrite instead of duplicate insertion
        - Independence from embedding content

        Changing this function breaks incremental indexing.
        """
        digest = blake2b(
            f"{document_id}:{chunk_index}".encode(),
            digest_size=8,
        ).digest()
        return int.from_bytes(digest, "big", signed=False)

    def store_chunks(self, chunks: List[Chunk]) -> None:
        """
        Insert or update chunk embeddings.

        Behaviour
        ---------
        - Upserts vectors (overwrite if exists)
        - Skips chunks without vectors
        - Stores text and metadata as payload
        - Does not remove missing chunks (handled by delete_document)

        This operation is idempotent.
        """
        self._ensure_connected()

        if not chunks:
            return

        points: List[PointStruct] = []

        for chunk in chunks:
            if not chunk.vector:
                continue

            payload = {
                DOC_ID: chunk.document_id,
                CHUNK_INDEX: chunk.chunk_index,
                TEXT: chunk.text,
                **(chunk.metadata or {}),
            }

            points.append(
                PointStruct(
                    id=self._point_id(chunk.document_id, chunk.chunk_index),
                    vector=list(chunk.vector),
                    payload=payload,
                )
            )
        if points:
            self._client().upsert(collection_name=self._collection(), points=points)


    def similarity_search(
        self,
        vector: Sequence[float],
        limit: int = 10,
    ) -> List[Chunk]:
        """
        Perform semantic nearest-neighbour search.

        Returns
        -------
        List[Chunk]
            Ordered by cosine similarity descending.

        Notes
        -----
        - Returned chunks DO NOT include stored embeddings
        - Metadata and text are preserved
        - Results are deterministic for identical index state
        """
        self._ensure_connected()

        response = self._client().query_points(
            collection_name=self._collection(),
            query=list(vector),
            limit=limit,
            with_payload=True,
            with_vectors=False,
        )


        results: List[Chunk] = []

        for point in response.points:
            payload = point.payload or {}

            results.append(
                Chunk(
                    document_id=payload[DOC_ID],
                    chunk_index=payload[CHUNK_INDEX],
                    text=payload.get(TEXT, ""),
                    vector=(),  # never return query vector
                    metadata={
                        k: v for k, v in payload.items()
                        if k not in (DOC_ID, CHUNK_INDEX, TEXT)
                    },
                )
            )

        return results

    def get_document_chunks(self, document_id: DocumentId) -> List[Chunk]:
        """
        Retrieve all chunks belonging to a document.

        Returns chunks ordered by chunk_index to reconstruct document order.
        """
        self._ensure_connected()

        filt = Filter(
            must=[FieldCondition(key=DOC_ID, match=MatchValue(value=document_id))]
        )

        chunks: List[Chunk] = []
        offset = None

        while True:
            records, offset = self._client().scroll(
                collection_name=self._collection(),
                scroll_filter=filt,
                with_payload=True,
                with_vectors=False,
                limit=512,
                offset=offset,
            )


            for r in records:
                payload = r.payload or {}

                chunks.append(
                    Chunk(
                        document_id=payload[DOC_ID],
                        chunk_index=payload[CHUNK_INDEX],
                        text=payload.get(TEXT, ""),
                        vector=(),
                        metadata={
                            k: v for k, v in payload.items()
                            if k not in (DOC_ID, CHUNK_INDEX, TEXT)
                        },
                    )
                )

            if offset is None:
                break

        return sorted(chunks, key=lambda c: c.chunk_index)

    def delete_document(self, document_id: DocumentId) -> int:
        """
        Permanently remove all vectors for a document.

        Guarantees
        ----------
        After completion, no chunk from this document will appear
        in similarity_search() results.

        Returns
        -------
        int
            Number of deleted chunks.
        """

        self._ensure_connected()

        chunks = self.get_document_chunks(document_id)
        if not chunks:
            return 0

        filt = Filter(
            must=[FieldCondition(key=DOC_ID, match=MatchValue(value=document_id))]
        )

        self._client().delete(
            collection_name=self._collection(),
            points_selector=filt,
        )


        return len(chunks)

    def _client(self) -> QdrantClient:
        self._ensure_connected()
        if self.client is None:
            raise RuntimeError("QdrantDatastore not connected: client missing")
        return self.client

    def _collection(self) -> str:
        self._ensure_connected()
        if self.collection is None:
            raise RuntimeError("QdrantDatastore not connected: collection missing")
        return self.collection

    def _vector_size(self) -> int:
        self._ensure_connected()
        if self.vector_size is None:
            raise RuntimeError("QdrantDatastore not connected: vector_size missing")
        return self.vector_size